# aph — Autopoiesis devops entrypoint.
#
# This file is aph-owned and has no upstream counterpart, so it never conflicts
# on an upstream sync. Every aph deployment action lives here rather than in the
# root package.json, whose scripts belong to deepseek-harness.
#
# Branches: `upstream` mirrors deepseek-harness, `dev` integrates, `main` is
# production. `install` deploys origin/main as fetched; `dev` serves the working
# tree. See APH.md.

APH_REPO     ?= $(CURDIR)
APH_PREFIX   ?= $(HOME)/.local/share/aph
APH_BINDIR   ?= $(HOME)/.local/bin
APH_HOME     ?= $(HOME)/.aph
APH_DEV_HOME ?= $(CURDIR)/.aph
APH_DOMAIN     ?= autopoiesis.feldhofer.cc
APH_DEV_DOMAIN ?= staging-autopoiesis.feldhofer.cc
APH_PORT       ?= 16720
APH_DEV_PORT   ?= 16721
APH_LAUNCHER   := $(APH_BINDIR)/aph

# The staging service serves origin/dev persistently. `make dev` is the
# interactive working-tree server on the same port, so it takes staging over
# only while the service is stopped; the port guard reports the conflict.
APH_STAGING_PREFIX    ?= $(HOME)/.local/share/aph-staging
APH_STAGING_HOME      ?= $(HOME)/.aph-staging
APH_WORKSPACE         ?= $(HOME)/.local/share/aph-workspace
APH_STAGING_WORKSPACE ?= $(HOME)/.local/share/aph-staging-workspace

APH_UNIT_DIR     ?= $(HOME)/.config/systemd/user
APH_UNIT         := aph.service
APH_STAGING_UNIT := aph-staging.service
APH_UNIT_SRC     := aph/systemd/aph-web.service.in

# systemd starts the unit with no shell, so node is resolved to a real path and
# its installation prefix is bind-mounted read-only past ProtectHome=tmpfs.
APH_NODE      := $(shell readlink -f "$$(command -v node)")
APH_NODE_BIN  := $(shell dirname "$(APH_NODE)")
APH_NODE_ROOT := $(shell n='$(APH_NODE)'; if [ "$${n#*/.linuxbrew/}" != "$$n" ]; then printf '%s/.linuxbrew' "$${n%%/.linuxbrew/*}"; else dirname "$$(dirname "$$n")"; fi)

# The web surface rejects --host 0.0.0.0 by design; the tunnel is the only ingress.
APH_HOST := 127.0.0.1

# Requests arrive from cloudflared carrying the public Host header, which the
# browser-trust fence refuses unless the authority is declared. This is the
# fence's own config seam, not a weakening of it: privileged methods stay
# pinned to loopback either way, and an undeclared authority is still refused.
# `--trusted-host` is variadic, so it always goes last on the command line.
APH_TRUST     = --trusted-host $(APH_DOMAIN)
APH_DEV_TRUST = --trusted-host $(APH_DEV_DOMAIN)

# A port held by another process is a manual cutover, never something make
# takes: the dsaph deployment serves 16720/16721 today.
check_port = @if command -v ss >/dev/null 2>&1 && ss -ltn 2>/dev/null | grep -qE '127\.0\.0\.1:$(1)([[:space:]]|$$)'; then echo 'aph: port $(1) is already served by another process; stop it or override $(2)' >&2; exit 1; fi

.DEFAULT_GOAL := help
.PHONY: help doctor install install-staging uninstall serve build dev dev-run units enable disable start stop restart status logs sync-upstream check check-all clean

help: ## Show available targets
	@echo 'aph — Autopoiesis'
	@echo
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'
	@echo
	@echo 'Production : $(APH_PREFIX) (origin/main), state $(APH_HOME), port $(APH_PORT)'
	@echo 'Development: $(APH_REPO) (working tree), state $(APH_DEV_HOME), port $(APH_DEV_PORT)'

doctor: ## Report toolchain, branch, and install state
	@echo 'node    : $(shell node -v 2>/dev/null || echo MISSING)'
	@echo 'pnpm    : $(shell pnpm -v 2>/dev/null || echo MISSING)'
	@echo 'branch  : $(shell git -C $(APH_REPO) rev-parse --abbrev-ref HEAD)'
	@echo 'remotes : $(shell git -C $(APH_REPO) remote | tr '\n' ' ')'
	@echo 'prefix  : $(APH_PREFIX) [$(shell test -e $(APH_PREFIX) && echo present || echo absent)]'
	@echo 'launcher: $(APH_LAUNCHER) [$(shell test -x $(APH_LAUNCHER) && echo present || echo absent)]'
	@echo 'aph home: $(APH_HOME) [$(shell test -d $(APH_HOME) && echo present || echo absent)]'
	@echo 'main    : $(APH_DOMAIN) -> $(APH_HOST):$(APH_PORT) [$(shell ss -ltn 2>/dev/null | grep -qE '127\.0\.0\.1:$(APH_PORT)([[:space:]]|$$)' && echo 'port busy' || echo 'port free')]'
	@echo 'staging : $(APH_DEV_DOMAIN) -> $(APH_HOST):$(APH_DEV_PORT) [$(shell ss -ltn 2>/dev/null | grep -qE '127\.0\.0\.1:$(APH_DEV_PORT)([[:space:]]|$$)' && echo 'port busy' || echo 'port free')]'
	@case ":$$PATH:" in *":$(APH_BINDIR):"*) ;; \
		*) echo; echo 'warning: $(APH_BINDIR) is not on PATH' ;; esac

install: ## Deploy origin/main and install the aph launcher
	@sh aph/bin/deploy-tree.sh '$(APH_REPO)' '$(APH_PREFIX)' origin/main
	@mkdir -p '$(APH_HOME)' '$(APH_WORKSPACE)' '$(APH_BINDIR)'
	@printf '%s\n' \
		'#!/bin/sh' \
		'# Generated by aph `make install`. Re-run make install to update.' \
		'exec env DSH_HOME="$(APH_HOME)" node "$(APH_PREFIX)/apps/cli/lib/bin.js" "$$@"' \
		> '$(APH_LAUNCHER)'
	@chmod +x '$(APH_LAUNCHER)'
	@echo "==> installed $(APH_LAUNCHER)"
	@$(MAKE) --no-print-directory doctor

install-staging: ## Deploy origin/dev as the staging service tree
	@sh aph/bin/deploy-tree.sh '$(APH_REPO)' '$(APH_STAGING_PREFIX)' origin/dev
	@mkdir -p '$(APH_STAGING_HOME)' '$(APH_STAGING_WORKSPACE)'

uninstall: ## Remove the launcher and production checkout, keeping state
	@rm -f '$(APH_LAUNCHER)'
	@if [ -e '$(APH_PREFIX)/.git' ]; then git -C $(APH_REPO) worktree remove --force '$(APH_PREFIX)'; fi
	@echo 'removed launcher and checkout; $(APH_HOME) left intact'

serve: ## Serve the installed production build (main)
	@test -x '$(APH_LAUNCHER)' || { echo 'not installed; run: make install' >&2; exit 1; }
	$(call check_port,$(APH_PORT),APH_PORT)
	@'$(APH_LAUNCHER)' web --host $(APH_HOST) --port $(APH_PORT) $(APH_TRUST)

build: ## Build the working tree
	@pnpm run build

dev: build dev-run ## Build and serve the working tree (staging)

dev-run: ## Serve the working tree without rebuilding
	@mkdir -p '$(APH_DEV_HOME)'
	$(call check_port,$(APH_DEV_PORT),APH_DEV_PORT)
	@DSH_HOME='$(APH_DEV_HOME)' node --import tsx/esm apps/cli/src/bin.ts \
		web --host $(APH_HOST) --port $(APH_DEV_PORT) $(APH_DEV_TRUST)

units: ## Render the systemd user units from the template
	@sh aph/bin/render-unit.sh '$(APH_UNIT_SRC)' '$(APH_UNIT_DIR)/$(APH_UNIT)' \
		'aph production web service' '$(APH_NODE)' '$(APH_NODE_BIN)' '$(APH_NODE_ROOT)' \
		'$(APH_PREFIX)' '$(APH_HOME)' '$(APH_WORKSPACE)' 'aph' '$(APH_PORT)' '$(APH_DOMAIN)'
	@sh aph/bin/render-unit.sh '$(APH_UNIT_SRC)' '$(APH_UNIT_DIR)/$(APH_STAGING_UNIT)' \
		'aph staging web service' '$(APH_NODE)' '$(APH_NODE_BIN)' '$(APH_NODE_ROOT)' \
		'$(APH_STAGING_PREFIX)' '$(APH_STAGING_HOME)' '$(APH_STAGING_WORKSPACE)' 'aph-staging' '$(APH_DEV_PORT)' '$(APH_DEV_DOMAIN)'
	@systemctl --user daemon-reload

enable: units ## Render the units and enable both services at login
	@systemctl --user enable $(APH_UNIT) $(APH_STAGING_UNIT)

disable: ## Stop both services and disable them at login
	@systemctl --user disable --now $(APH_UNIT) $(APH_STAGING_UNIT)

start: ## Start both services now
	@systemctl --user start $(APH_UNIT) $(APH_STAGING_UNIT)

stop: ## Stop both services now
	@systemctl --user stop $(APH_UNIT) $(APH_STAGING_UNIT)

restart: ## Restart both services now
	@systemctl --user restart $(APH_UNIT) $(APH_STAGING_UNIT)

status: ## Report both services' unit state
	@systemctl --user status --no-pager $(APH_UNIT) $(APH_STAGING_UNIT) || true

logs: ## Follow both services' logs
	@journalctl --user -u $(APH_UNIT) -u $(APH_STAGING_UNIT) -f

sync-upstream: ## Fast-forward the upstream branch and open a sync branch off dev
	@git -C $(APH_REPO) diff --quiet || { echo 'working tree is dirty; commit or stash first' >&2; exit 1; }
	@git -C $(APH_REPO) fetch upstream
	@git -C $(APH_REPO) fetch origin
	@git -C $(APH_REPO) switch upstream
	@git -C $(APH_REPO) merge --ff-only upstream/master
	@git -C $(APH_REPO) push origin upstream
	@git -C $(APH_REPO) switch -c 'sync/upstream-$(shell date +%Y%m%d)' origin/dev
	@git -C $(APH_REPO) merge upstream
	@echo
	@echo 'merged upstream into a sync branch; changes reach dev by PR:'
	@echo '  git push -u origin HEAD && gh pr create --base dev'

check: ## Run the pre-push checks (typecheck, lint, unit tests)
	@pnpm run typecheck
	@pnpm run lint
	@pnpm run test

check-all: ## Run every repository gate (slow; CI owns this signal)
	@pnpm run check:all

clean: ## Remove build outputs from the working tree
	@pnpm run clean
